### ISSUE TITLE
Add file permissions verification

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#32] opened 2015-04-17 23:30 UTC
Original [issue 32](https://code.google.com/p/giraffa/issues/detail?id=32) created by shvachko on 2012-09-18T02:20:18.000Z:

Currently we store permissions in the form of FSPermissions but we do not verify the permissions when we attempt to read, overwrite, etc. We should add those checks in place and write a unit test to verify that it works.

**Comment by shvachko** [comment] 2015-04-17 23:30
Comment [#1](https://code.google.com/p/giraffa/issues/detail?id=32#c1) originally posted by shvachko on 2012-09-24T17:53:18.000Z:

I think the correct psuedo code is along the lines of:

public void create(...FsPerms perms...) {
  if(OVERWRITE)
    if(node == null)
       ...do regular create...
    if(node.exists())
       if(perms.canWrite && node.getUserName().equals(clientName)
        ...do overwrite..
       else
        ...throw perms exception...
}

Essentially some sort of check like this needs to be inserted at the NamespaceProcessor layer for create, mkdirs... anywhere that reading or writing to a file is required.

**Comment by octo47** [comment] 2015-05-07 09:21
I'd like to take this one.
I'm going to make FsPermissionChecker class and use it instead of inplace checks.
That allows us to write unit test for permission checks.

**Comment by shvachko** [comment] 2015-05-08 00:46
Yes `FsPermissionChecker` is the way to go, similar to similar to `FSN.checkPermission()`

**Comment by octo47** [comment] 2015-05-20 17:23
Preliminary patch. Tests still need to be fixed.

**Comment by shvachko** [comment] 2015-05-21 00:37
I reviewed the patch first (see comments below) and then realized we should not resolve the path while checking permissions. This was mistakenly done in HDFS and actually fixed now in 2.7.0 by HDFS-7474.

In Giraffa case resolving the path is a distributed operation. It would be wrong doing it on the sever. Ideally we should check permissions **while** resolving the path. That is when you get an INode on the path, you check if the user has permissions to access that INode. So `FsPermissionChecker` should work on a single INode without `INodeResolver`. We should be able to do it when we implement inodeID-based RowKeys.

_For now, can we focus on checking permissions only on the parent and on the INode itself? That is mkdir() checks if the user has write access to the parent, etc. This is incomplete, but a step forward._

My other comments on the patch:
1. `GRFA_PERMISSIONS_ENABLED_KEY` and `GRFA_PERMISSIONS_ENABLED_DEFAULT` should be defined via the respective `DFSConfigKeys` constants. Not just the same values.
2. `getSuperGroup()` should return `FS_SUPERGROUP`.
3. Too bad we cannot use hdfs.FsPermissionChecker. But if you copy anything could you do it literally, without reformatting or renaming. I see you reformatted big Javadoc for `checkPermission()`. It does look nice, but it will be hard to compare with the original, when it changes.
4. No need for `INodeResolver` as per comment above.
5. Add Apache license to FsPermissionChecker.
6. Quite a few blank line/spaces changes. This can make merging with other work-in-progress branches harder.

**Comment by octo47** [comment] 2015-05-21 06:35
Thank you for reviewing, Konstantin.
1. Ok (but it will introduce depdendency to hadoop-hdfs project)
2. Ok.
3. I used copy to get initial class. There are changes in methods parameters and how children/parents handled. I will return reformatted javadoc. But not sure how we can reuse unhcanged FsPermissionChecker.
4. We don't have INodeDirectory and methods for working with. What wrong with separate interface for that?
5. Ok.
6. Ok.

**Comment by shvachko** [comment] 2015-05-21 18:39
> it will introduce depdendency to hadoop-hdfs project

Giraffa is fully compatible with HDFS on the client side and configuration-wise, so it is not a dependency, but rather a support of standard HDFS config parameters.

> What wrong with separate interface for that?

Nothing is wrong. But seems that you missed completely the upper part of my comment.

**Comment by octo47** [comment] 2015-05-21 20:25
Ok. Lets use constants and remove INodeResolver and checkSubAccess (there is place where resolver is to get children of the node).

**Comment by milandesai** [comment] 2015-06-11 07:27
Just confirming that I have taken over this issue as agreed last week and am continuing to build on Andrei's existing pull request. There are some tricky situations to capture so it is taking longer than expected, but I plan to finish it this weekend.

**Comment by milandesai** [comment] 2015-06-21 01:52
Finally finished this work. I apologize for the delay, this is much more complicated than it may appear at face value. All tests are passing, still need to check on the standalone install. The pull request includes the fix for #173 which is needed to get tests to pass (for me). It is on a new branch, `issue-32b`, because it is not based off of the current `issue-32` branch. Due to the enormity of changes needed, both design and implementation related, it was easiest for me to start from scratch.

**Comment by milandesai** [comment] 2015-06-21 01:53
# Permissions in Giraffa

The following document outlines the design and implementation of permissions in Giraffa. The first section goes over the initial design constraint, followed by a table displaying the access privileges required for each operation. Then we discuss additional design constraints followed by a description of the implementation and testing.

## Preliminary Notes

To properly check permissions, we have to check the execute bit of the parent, grandparent, etc. This means each method would have to resolve the path into all of its INode components, an expensive operation. In Giraffa, path resolution is a distributed operation initiated by the client, so once this is properly implemented with INode IDs (see: #34), we can check execute permissions during the resolution. For now, we only consider the permission of the immediate parent directory. Otherwise, the permission model copies that of HDFS, which is based off BSD's permission design.

## Access Table

| OPERATION | src.parent | src | dst.parent | notes |
| --- | --- | --- | --- | --- |
| create | WX |  |  |  |
| create (overwrite) | X | W |  |  |
| delete | WX |  |  | check sticky bit of parent |
| delete (non-empty dir) | WX | RWX |  | check sticky bit of parent |
| getBlockLocations | X | R |  |  |
| getContentSummary | X |  |  |  |
| getFileInfo | X |  |  |  |
| getListing | X | RX |  |  |
| getPreferredBlockSize | X |  |  |  |
| isFileClosed | X |  |  |  |
| mkdirs | WX |  |  |  |
| rename | WX |  | WX | check sticky bit of parent |
| setOwner | X |  |  | must be superuser to change owner, member of new group to change group |
| setPermission | X |  |  | must be owner |
| setQuota |  |  |  | must be superuser |
| setReplication | X | W |  |  |
| setTimes | X | W |  |  |

## Additional Logic:
- superuser has full permissions
- create: If parent directories are created, those directories inherit permissions from the ancestor, plus RW for user.
- mkdirs: If parent directories are created, those directories are created with the given permission, plus RW for user.
- AccessControlExceptions take priority over all other Exceptions; i.e. they should be thrown before any FileNotFoundException, etc. is thrown.

## Implementation Considerations

Class `FSPermissionChecker` was created and is based off `FSPermissionChecker` in HDFS, but the implementations are so substantially different that it is not worth it to try to maintain syntax similarities with the HDFS version. The differences are based on the fact that we don't generate an INodesInPath object and don't resolve the entire path. The creation of a similar structure was avoided since in the future we intend to check parent permissions during the distributed path resolution. Additionally, care was needed to ensure that the number of INode retrievals was minimal, based on whether or not permissions were enabled. Finally, class `RpcUtil` had to be created in the package `hbase.ipc` to obtain the remote User information from the RpcServer.

## Testing

The class `TestDFSPermission` was reused for testing permissions (TestFSPermissionChecker is for ACLs, which we don't support). This test creates files and directories with random permissions, computes whether or not the different FileSystem operations should succeed, and then tests the operation. However, the test had to be mocked to ignore grandparent permission. Additionally, MiniHBaseCluster starts RegionServers using a fake User whose name is the current User appended with a 'hfs.$i', where $i is the index of the RegionServer. This messes up permission checking, so the functionality needed to be mocked out for all unit tests. However, this disallows the creation of multiple RegionServers in the minicluster, something that is needed for TestLeaseManagement, so TestLeaseManagement destroys the mock and disables permissions.

**Comment by milandesai** [comment] 2015-06-22 20:51
I tested this on the standalone install with multiple users and it works as designed.

**Comment by pjeli** [comment] 2015-06-25 19:14
- Should make more use of INodeManager.getParentINode().
- INode.isEmpty should always return false if it is a file and not a directory.
- INode.isEmpty needs to always be set when fetching the INode (and if its a directory) otherwise the method itself doesn't make much sense.
- RpcUtil -> HBaseRpcUtil.

**Comment by milandesai** [comment] 2015-06-26 00:36
Fixed all points. With regard to INode.isEmpty, agreed to use Boolean object where null indicates the value is unknown, as discussed offline.

**Comment by pjeli** [comment] 2015-06-26 18:10
- Since you've added a null possibility to isEmpty() you should do a null check where you use that method and log an error. I saw that such a check was missing.

**Comment by milandesai** [comment] 2015-06-29 22:48
I added an assertion as opposed to an Exception/log since in this case `isEmpty` is guaranteed to never return null. I also included in the JavaDoc for `INodeManager.getDirectories` the guarantee that all returned nodes will have the isEmpty field set. Merged with trunk and all tests are passing.

**Comment by pjeli** [comment] 2015-07-01 19:14
+1! Really good.

**Comment by milandesai** [comment] 2015-07-01 19:21
Thanks for the review @zero45. Committed to trunk as `5f59ca3859b61f79dd9c77d5636b3fda59d79392`.

**Closed as completed by milandesai** 2015-07-01 19:21 UTC
Labels: Priority-Medium, Type-Defect
